Fixing some issues with coco split utility
Layout-Parser/layout-model-training pull request #2
Opened 2021-05-26 16:43 UTC by nasheedyasin

Fixing the issue with the coco split utility failing when info and license fields aren't available.

2021-06-07 15:01 UTC, lolipopshock commented
Thank you very much! I will check it ASAP!

2021-06-16 14:24 UTC, lolipopshock requested changes
Great work! I've added a few comments on some details - other than that it looks good to me!

2021-06-16 14:24 UTC, lolipopshock commented on utils/cocosplit.py
> +parser.add_argument('--s', dest='split_ratio', type=float, required=True,
Thanks for the change - could we remove one `-` for the abbreviated name? or just use `--split-ratio`.

2021-06-16 14:24 UTC, lolipopshock commented on utils/cocosplit.py
> +        coco.update({'images': tr,
Clever way for handling the metadata fields!

2021-06-16 14:24 UTC, lolipopshock commented on tools/train_net.py
> +    os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
I think Detectron2 will automatically handle the creation of the new directories. But good to add!

2021-06-16 14:24 UTC, lolipopshock commented on tools/train_net.py
>      # Extra Configurations for dataset names and paths
Could we keep the spacing before `default` to make the configs visually recognizable? I think you could add `fmt:off` and `fmt:on` before and after the parser specification to disable the auto-listing. Thanks!

2021-06-16 15:35 UTC, nasheedyasin commented on utils/cocosplit.py
>          coco = json.load(annotations)
Ah yes, I think this slipped my mind.

2021-06-16 15:35 UTC, nasheedyasin commented on utils/cocosplit.py
> +        coco.update({'images': tr,
Haha, thanks :)

2021-06-16 15:43 UTC, nasheedyasin commented
Hey, have added the changes as suggested :)
Thanks for the encouragement xD My first open src PR

2021-06-17 14:30 UTC, lolipopshock approved these changes
LGTM! Thanks!

2021-06-17 14:44 UTC, nasheedyasin commented on tools/train_net.py
> +    augs.append(T.RandomRotation(angle=[-90.0, 0.0]))
Well, the I misread the detectron2 documentation and thought that the rotation was anti-clockwise about the center. It was in fact clockwise.

[-90, 90] could be a good idea, but it really depends on the data that the trainer has got. In my case, [-90, 0] sufficed as there was a really low probability of encountering documents that were rotated clockwise 90 degrees. The value there should be basically a placeholder that the use could fill.

I will try to see if there is a way to allow the user to choose this range from the config.yaml file, but so far I have been unable to find a non-code way to do it.

Also I consciously avoided having a 180 degree range as I noticed that having upside down text was bad for the model when working on textual images.

2021-06-20 18:11 UTC, merged

2021-06-20 18:14 UTC, lolipopshock commented on tools/train_net.py
> +    augs.append(T.RandomRotation(angle=[-90.0, 0.0]))
Gotcha - thanks! And I agree with you - document images are super sensitive to the orientation of the training data - in one earlier experiment, even a horizontal flip augmentation can decrease the model performance. And probably the rotation augmentation is unnecessary in certain cases (for example, for newspaper images, where almost all the newspaper are positioned in a certain way).